version: "3"
services:
  mongo:
    image: mongo:6.0.1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
      
  user:
    image: user-service:1.0
    build:
      context: .
      dockerfile: cmd/user/Dockerfile
    command:
      - -http=:8000
      - -mongodb=mongodb://mongoadmin:secret@mongo:27017
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy