version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.38.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  
  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5